export const FETCH_ANNOUNCEMENT = "FETCH_ANNOUNCEMENT";
export const FETCH_ANNOUNCEMENT_BY_YEAR = "FETCH_ANNOUNCEMENT_BY_YEAR";
export const CREATE_ANNOUNCEMENT = "CREATE_ANNOUNCEMENT";
export const UPDATE_ANNOUNCEMENT = "UPDATE_ANNOUNCEMENT";
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";