export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_PROFILE_BY_YEAR = "FETCH_PROFILE_BY_YEAR";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";