import { makeStyles } from '@material-ui/core';
import logo from '../../assets/iiit_surat.png';

export default makeStyles((theme) => ({

    box: {
        backgroundColor: 'rgba(32, 33, 53, 1)',
        // maxWidth: '60em',
        height: '35vh',
        borderRadius: '16px',
        overflowX: 'hidden',
        display: 'flex',
        flexWrap: 'nowrap',
        alignItems: 'center',
        overflowY: 'hidden',
        position: 'relative',
        paddingLeft: '1rem',
        paddingRight: 0,
    },
    heading: {
        color: "#fff",
        fontWeight: 500,
    },
    container: {
        padding: 0,
        paddingRight: '2rem',
        position: 'absolute',
        top: '50%',
        transform: 'translateY(-40%)',
    },
    wrapper: {
        // background: "linear-gradient(180.59deg, rgba(0, 0, 0, 0) 0.51%, #000000 118.35%)",
        position: 'relative',
    },
    cardroot: {
        width: '16em',
        height: '32vh',
        borderRadius: '10px',
        display: 'flex',
        flexDirection: 'column',
        alignText: 'left',
        justifyContent: 'flex-end',
        color: "#fff",
        // backgroundImage: ` linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)) ,url(${logo})`,
        backgroundSize: 'contain',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
        [theme.breakpoints.down('xs')]: {
            width: '13rem'
        },
    },
    infoContainer: {
        padding: '0.7em',
        textAlign: 'left',
    },
    content: {
        fontSize: '14px',
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        [theme.breakpoints.down('xs')]: {
            fontSize: '12px',
        },
    },
    btnContainer: {
        margin: 0,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingLeft: '0.7em',
    },
    btn: {
        fontSize: '14px',
        fontWeight: '500',
    },
    card2root: {
        width: '16em',
        height: '32vh',
        display: 'flex',
        flexDirection: 'column',
        borderRadius: '10px',
        alignText: 'left',
        justifyContent: 'flex-end',
        color: "#fff",
        background: 'linear-gradient(180.59deg, rgba(0, 0, 0, 0) 0.51%, #000000 118.35%)!important',
        [theme.breakpoints.down('xs')]: {
            width: '13rem',
        },
    },
    wrapper2: {
        display: 'flex',
        flexDirection: 'column',
        height: '32vh',
        justifyContent: 'space-between',
    },
    wrapper3: {
        display: 'flex',
        flexDirection: 'column',
        height: '32vh',
        justifyContent: 'space-between',

    },
    infoContainer2: {
        textAlign: 'left',
        padding: '0.7em',
        position: 'absolute',
        top: 0,
    },
    content2: {
        color: 'rgba(255,255,255,0.8)',
        fontSize: '14px',
        width: '16em',
        // height: '15vh',
        // whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        display: 'block',
        wordWrap: 'break-word',
        maxHeight: '8.4em',
        lineHeight: '1.2em',
    },
    btn2: {
        color: '#DF4401',
        fontSize: '14px',
        fontWeight: '500',
        cursor: 'pointer',
    },
    btnContainer2: {
        margin: 0,
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingLeft: '0.7em',
        paddingRight: '0.3em',
    },
    loading: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    popover: {
        background: 'rgba(32, 33, 53, 1)',
        // position: 'relative',
    },
    wrapperdiv: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        height: '25vh',
    },
    heading1: {
        fontWeight: '700',
        whiteSpace: 'nowrap',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    heading2: {
        fontWeight: '700',
        lineHeight: '1.2em',
        paddingBottom: '0.3em',
    },
    downloadlink: {
        textDecoration: 'none',
        color: '#fff',
    },
    editdiv: {
        // background: 'rgba(32, 33, 53, 1)',
        // borderRadius: '50%',
        // width: '7rem',
        // display: 'block',
        // position: 'absolute',
        // // top: '51%',
        // // left: '51%',
        // width: '100px',
        // height: '100px',
        // margin: '-51px',
        // background: 'red',
        // borderRadius: '51%',
        // textAlign: 'center',
        // lineHeight: '100px',
        // transform: 'rotate(46deg) translate(251px) rotate(-46deg)',
    },
    deletediv: {
        // background: 'rgba(32, 33, 53, 1)',
        // borderRadius: '50%',
        // width: '7rem',
        // display: 'block',
        // position: 'absolute',
        // // top: '51%',
        // // left: '51%',
        // width: '100px',
        // height: '100px',
        // margin: '-51px',
        // background: 'red',
        // borderRadius: '51%',
        // textAlign: 'center',
        // lineHeight: '100px',
        // transform: 'rotate(91deg) translate(251px) rotate(-91deg)',
    },
    // ////dark theme
    darkheading: {
        color: "#20213D",
        fontWeight: 500,
    },
    darkbox: {
        maxWidth: '60em',
        height: '35vh',
        borderRadius: '16px',
        overflowX: 'hidden',
        display: 'flex',
        flexWrap: 'nowrap',
        alignItems: 'center',
        position: 'relative',
        paddingLeft: '1rem',
        paddingRight: 0,
        background: '#fff',
        overflow: 'hidden',
    }
}))